In [4]:
import numpy as np
import scipy.stats as sp

In [5]:
sample = np.random.normal(10, 5, 10)

In [6]:
sample

array([ 5.66027747,  3.98784061,  9.0147614 , 10.36977967, 13.25793833,
       11.50288367, 12.23164083, 10.93100664,  6.83296716,  6.70497986])

In [7]:
np.mean(sample)

9.049407562993967

In [9]:
sp.mode(sample)[0]

array([3.98784061])

In [11]:
np.min(sample)

3.987840612906872

In [12]:
np.max(sample)

13.257938326857918

In [15]:
np.quantile(sample, 0.25)

6.736976687626649

In [16]:
np.quantile(sample, 0.5)

9.692270532439142

In [17]:
np.median(sample)

9.692270532439142

In [18]:
sp.iqr(sample)

4.622937720458653

In [19]:
np.quantile(sample, 0.75) - np.quantile(sample, 0.25)

4.622937720458653

In [20]:
np.var(sample)

8.665749476374177

In [21]:
np.std(sample)

2.943764507628655

In [22]:
sp.skew(sample)

-0.24256913159090213

In [23]:
sp.kurtosis(sample)

-1.2546217421111647

In [34]:
np.random.randint(0,10,10)

array([7, 3, 0, 9, 8, 9, 6, 4, 8, 2])

In [28]:
arr1 = np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
arr2 = np.array([1, 4, 6, 7, 8, 9, 7, 5, 2, 3])
arr2

array([1, 4, 6, 7, 8, 9, 7, 5, 2, 3])

In [30]:
np.corrcoef(arr1, arr2)

array([[ 1.00000000e+00, -6.13076528e-18],
       [-6.13076528e-18,  1.00000000e+00]])